parameters:
    agile.host_env: "%agile_host_env%"
    agile.project_domain: "%agile_project_domain%"
    agile.project_url: "%agile_project_url%"
    agile.developer_email: "%agile_developer_email%"
    agile.contact_email: "%agile_contact_email%"
    agile.project_name: "%agile_project_name%"
    agile.project_title: "%agile_project_title%"
    agile.vagrant_ip: 192.168.33.5
    agile.email_sender_name: "%agile_email_sender_name%"
